# YAML CONFIG FILE
reference: 'demo/chr21.fa'
variant_sets:
    - type: "DEL"
      number: 5
      length_ranges: [[5000, 10000]]
    - type: "DUP"
      number: 5
      length_ranges: [[5000, 10000]]
    - type: "INV"
      number: 5
      length_ranges: [[5000, 10000]]
    - type: "A->aa" # inverted duplication
      number: 5
      length_ranges: [[ 5000, 10000]]
    - type: "AB->AbbA" # custom complex variant
      number: 5
      length_ranges: [[5000, 10000], [5000, 10000]]